<?php

namespace App\Http\Controllers\Api\v1\Ecommerce;

use App\Models\Post;
use App\Models\Ecommerce\Item;

use Illuminate\Support\Str;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class TestController extends Controller
{
    public function submit(Request $request) {
        $data = [
            0 => [
                'title' => 'Tričko Jawa 50/23 Mustang',
                'teaser' => 'Černé tričko s krátkým rukávem a s motivem Jawa Mustang ze 100% bavlny. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černé bavlněné tričko s motivem Jawa 50/23 Mustang - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Trika mají krátký rukáv, kulatý výstřih a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka je ze 100% bavlny a díky vyšší gramáži je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Tričko Jawa 50/23 Mustang',
                'post_seo_description' => 'Černé tričko s krátkým rukávem a s motivem Jawa Mustang ze 100% bavlny.',
                'post_seo_keywords' => 'jawa, jawa tričko, jawa dárek, jawa mustang, jawa 23, jawa 50, jawa 50/23',
                'term' => 1,
            ],1 => [
                'title' => 'Tričko Jawa 50/20 Pionýr',
                'teaser' => 'Černé tričko s krátkým rukávem a s motivem Jawa Pionýr ze 100% bavlny. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černé bavlněné tričko s motivem Jawa 50/20 Pionýr - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Trika mají krátký rukáv, kulatý výstřih a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka je ze 100% bavlny a díky vyšší gramáži je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Tričko Jawa 50/20 Pionýr',
                'post_seo_description' => 'Černé tričko s krátkým rukávem a s motivem Jawa Pionýr ze 100% bavlny.',
                'post_seo_keywords' => 'jawa, jawa tričko, jawa dárek, jawa pionýr, jawa 20, jawa 50, jawa 50/20',
                'term' => 1,
            ],3 => [
                'title' => 'Tričko Jawa 50/21 Pionýr',
                'teaser' => 'Černé tričko s krátkým rukávem a s motivem Jawa Pionýr ze 100% bavlny. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černé bavlněné tričko s motivem Jawa 50/21 Pionýr - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Trika mají krátký rukáv, kulatý výstřih a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka je ze 100% bavlny a díky vyšší gramáži je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Tričko Jawa 50/21 Pionýr',
                'post_seo_description' => 'Černé tričko s krátkým rukávem a s motivem Jawa Pionýr ze 100% bavlny.',
                'post_seo_keywords' => 'jawa, jawa tričko, jawa dárek, jawa pionýr, jawa 21, jawa 50, jawa 50/21',
                'term' => 1,
            ],5 => [
                'title' => 'Tričko Jawa 50/555 Pařez',
                'teaser' => 'Černé tričko s krátkým rukávem a s motivem Jawa Pařez ze 100% bavlny. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černé bavlněné tričko s motivem Jawa 50/555 Pařez - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Trika mají krátký rukáv, kulatý výstřih a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka je ze 100% bavlny a díky vyšší gramáži je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Tričko Jawa 50/555 Pařez',
                'post_seo_description' => 'Černé tričko s krátkým rukávem a s motivem Jawa Pařez ze 100% bavlny.',
                'post_seo_keywords' => 'jawa, jawa tričko, jawa dárek, jawa pionyr, jawa pařez, jawa 555, jawa 50, jawa 50/555',
                'term' => 1,
            ],6 => [
                'title' => 'Tričko Stadion S11',
                'teaser' => 'Černé tričko s krátkým rukávem a s motivem Stadion S11 ze 100% bavlny. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černé bavlněné tričko s motivem Stadion S11 - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Trika mají krátký rukáv, kulatý výstřih a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka je ze 100% bavlny a díky vyšší gramáži je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Tričko Stadion S11',
                'post_seo_description' => 'Černé tričko s krátkým rukávem a s motivem Stadion S11 ze 100% bavlny.',
                'post_seo_keywords' => 'jawa, jawa tričko, jawa dárek, stadion, stadion s11',
                'term' => 1,
            ],7 => [
                'title' => 'Tričko Stadion S22',
                'teaser' => 'Černé tričko s krátkým rukávem a s motivem Stadion S22 ze 100% bavlny. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černé bavlněné tričko s motivem Stadion S22 - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Trika mají krátký rukáv, kulatý výstřih a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka je ze 100% bavlny a díky vyšší gramáži je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Tričko Stadion S22',
                'post_seo_description' => 'Černé tričko s krátkým rukávem a s motivem Stadion S22 ze 100% bavlny.',
                'post_seo_keywords' => 'jawa, jawa tričko, jawa dárek, stadion, stadion s22',
                'term' => 1,
            ],8 => [
                'title' => 'Tričko Babetta 207',
                'teaser' => 'Černé tričko s krátkým rukávem a s motivem Babetta 207 ze 100% bavlny. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černé bavlněné tričko s motivem Babetta 207 - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Trika mají krátký rukáv, kulatý výstřih a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka je ze 100% bavlny a díky vyšší gramáži je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Tričko Babetta 207',
                'post_seo_description' => 'Černé tričko s krátkým rukávem a s motivem Babetta 207 ze 100% bavlny.',
                'post_seo_keywords' => 'jawa, jawa tričko, jawa dárek, babetta, babetta 207',
                'term' => 1,
            ],9 => [
                'title' => 'Tričko Babetta 210',
                'teaser' => 'Černé tričko s krátkým rukávem a s motivem Babetta 210 ze 100% bavlny. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černé bavlněné tričko s motivem Babetta 210 - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Trika mají krátký rukáv, kulatý výstřih a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka je ze 100% bavlny a díky vyšší gramáži je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Tričko Babetta 210',
                'post_seo_description' => 'Černé tričko s krátkým rukávem a s motivem Babetta 210 ze 100% bavlny.',
                'post_seo_keywords' => 'jawa, jawa tričko, jawa dárek, babetta, babetta 210',
                'term' => 1,
            ],10 => [
                'title' => 'Tričko Jawa Kývačka',
                'teaser' => 'Černé tričko s krátkým rukávem a s motivem Jawa Kývačka ze 100% bavlny. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černé bavlněné tričko s motivem Jawa Kývačka - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Trika mají krátký rukáv, kulatý výstřih a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka je ze 100% bavlny a díky vyšší gramáži je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Tričko Jawa Kývačka',
                'post_seo_description' => 'Černé tričko s krátkým rukávem a s motivem Jawa Kývačka ze 100% bavlny.',
                'post_seo_keywords' => 'jawa, jawa tričko, jawa dárek, kývačka, jawa kývačka',
                'term' => 1,
            ],11 => [
                'title' => 'Tričko Jawa Panelka',
                'teaser' => 'Černé tričko s krátkým rukávem a s motivem Jawa Panelka ze 100% bavlny. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černé bavlněné tričko s motivem Jawa Panelka - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Trika mají krátký rukáv, kulatý výstřih a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka je ze 100% bavlny a díky vyšší gramáži je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Tričko Jawa Panelka',
                'post_seo_description' => 'Černé tričko s krátkým rukávem a s motivem Jawa Panelka ze 100% bavlny.',
                'post_seo_keywords' => 'jawa, jawa tričko, jawa dárek, panelka, jawa panelka, jawa 250',
                'term' => 1,
            ],12 => [
                'title' => 'Tričko Jawa Pérák',
                'teaser' => 'Černé tričko s krátkým rukávem a s motivem Jawa Pérák ze 100% bavlny. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černé bavlněné tričko s motivem Jawa Pérák - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Trika mají krátký rukáv, kulatý výstřih a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka je ze 100% bavlny a díky vyšší gramáži je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Tričko Jawa Pérák',
                'post_seo_description' => 'Černé tričko s krátkým rukávem a s motivem Jawa Pérák ze 100% bavlny.',
                'post_seo_keywords' => 'jawa, jawa tričko, jawa dárek, pérák, jawa pérák, jawa 250',
                'term' => 1,
            ],13 => [
                'title' => 'Tričko Jawa 350/634 Konopnice',
                'teaser' => 'Černé tričko s krátkým rukávem a s motivem Jawa 350/634 Konopnice ze 100% bavlny. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černé bavlněné tričko s motivem Jawa 350/634 Konopnice - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Trika mají krátký rukáv, kulatý výstřih a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka je ze 100% bavlny a díky vyšší gramáži je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Tričko Jawa 350/634 Konopnice',
                'post_seo_description' => 'Černé tričko s krátkým rukávem a s motivem Jawa 350/634 Konopnice ze 100% bavlny.',
                'post_seo_keywords' => 'jawa, jawa tričko, jawa dárek, konopnice, jawa konopnice, jawa 350, jawa 350/634, 350/634',
                'term' => 1,
            ],14 => [
                'title' => 'Tričko Jawa 350/638',
                'teaser' => 'Černé tričko s krátkým rukávem a s motivem Jawa 350/638 ze 100% bavlny. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černé bavlněné tričko s motivem Jawa 350/638 - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Trika mají krátký rukáv, kulatý výstřih a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka je ze 100% bavlny a díky vyšší gramáži je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Tričko Jawa 350/638',
                'post_seo_description' => 'Černé tričko s krátkým rukávem a s motivem Jawa 350/638 ze 100% bavlny.',
                'post_seo_keywords' => 'jawa, jawa tričko, jawa dárek, jawa 350, jawa 350/638, 350/638',
                'term' => 1,
            ],16 => [
                'title' => 'Tričko Jawa 500 OHC',
                'teaser' => 'Černé tričko s krátkým rukávem a s motivem Jawa 500 OHC ze 100% bavlny. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černé bavlněné tričko s motivem Jawa 500 OHC - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Trika mají krátký rukáv, kulatý výstřih a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka je ze 100% bavlny a díky vyšší gramáži je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Tričko Jawa 500 OHC',
                'post_seo_description' => 'Černé tričko s krátkým rukávem a s motivem Jawa 500 OHC ze 100% bavlny.',
                'post_seo_keywords' => 'jawa, jawa tričko, jawa dárek, jawa 500, jawa 500 ohc, 500 ohc',
                'term' => 1,
            ],17 => [
                'title' => 'Tričko ČZ 175/501 Prase',
                'teaser' => 'Černé tričko s krátkým rukávem a s motivem ČZ 175/501 Prase ze 100% bavlny. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černé bavlněné tričko s motivem ČZ 175/501 (502, 505) Prase - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Trika mají krátký rukáv, kulatý výstřih a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka je ze 100% bavlny a díky vyšší gramáži je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Tričko ČZ 175/501 Prase',
                'post_seo_description' => 'Černé tričko s krátkým rukávem a s motivem ČZ 175/501 Prase ze 100% bavlny.',
                'post_seo_keywords' => 'jawa, jawa tričko, jawa dárek, čz, čezeta, čz 175, čz 501, čz 502, čz 505, čz 175/501, 175/501, tričko čezeta, tričko čz',
                'term' => 1,
            ],18 => [
                'title' => 'Tričko ČZ 125/476, 175/477',
                'teaser' => 'Černé tričko s krátkým rukávem a s motivem ČZ 125/476, 175/477 ze 100% bavlny. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černé bavlněné tričko s motivem ČZ 125/476, 175/477 - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Trika mají krátký rukáv, kulatý výstřih a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka je ze 100% bavlny a díky vyšší gramáži je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Tričko ČZ 125/476, 175/477',
                'post_seo_description' => 'Černé tričko s krátkým rukávem a s motivem ČZ 125/476, 175/477 ze 100% bavlny.',
                'post_seo_keywords' => 'jawa, jawa tričko, jawa dárek, čz, čezeta, čz 175, čz 125, čz 476, čz 477, 125/476, 175/477, tričko čezeta, tričko čz',
                'term' => 1,
            ],19 => [
                'title' => 'Tričko ČZ 125/487, 175/488',
                'teaser' => 'Černé tričko s krátkým rukávem a s motivem ČZ 125/487, 175/488 ze 100% bavlny. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černé bavlněné tričko s motivem ČZ 125/487, 175/488 - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Trika mají krátký rukáv, kulatý výstřih a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka je ze 100% bavlny a díky vyšší gramáži je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Tričko ČZ 125/487, 175/488',
                'post_seo_description' => 'Černé tričko s krátkým rukávem a s motivem ČZ 125/487, 175/488 ze 100% bavlny.',
                'post_seo_keywords' => 'jawa, jawa tričko, jawa dárek, čz, čezeta, čz 175, čz 125, čz 487, čz 488, 125/487, 175/488, tričko čezeta, tričko čz',
                'term' => 1,
            ],20 => [
                'title' => 'Tričko Simson S51',
                'teaser' => 'Černé tričko s krátkým rukávem a s motivem Simson S51 ze 100% bavlny. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černé bavlněné tričko s motivem Simson S51 - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Trika mají krátký rukáv, kulatý výstřih a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka je ze 100% bavlny a díky vyšší gramáži je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Tričko Simson S51',
                'post_seo_description' => 'Černé tričko s krátkým rukávem a s motivem Simson S51 ze 100% bavlny.',
                'post_seo_keywords' => 'jawa, jawa tričko, jawa dárek, simson, simson s51, s51, tričko simson s51',
                'term' => 1,
            ],21 => [
                'title' => 'Tričko MZ 150',
                'teaser' => 'Černé tričko s krátkým rukávem a s motivem MZ 150 ze 100% bavlny. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černé bavlněné tričko s motivem MZ 150 - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Trika mají krátký rukáv, kulatý výstřih a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka je ze 100% bavlny a díky vyšší gramáži je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Tričko MZ 150',
                'post_seo_description' => 'Černé tričko s krátkým rukávem a s motivem MZ 150 ze 100% bavlny.',
                'post_seo_keywords' => 'jawa, jawa tričko, jawa dárek, mz 150, tričko mz 150',
                'term' => 1,
            ],22 => [
                'title' => 'Tričko Velorex',
                'teaser' => 'Černé tričko s krátkým rukávem a s motivem Velorex ze 100% bavlny. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černé bavlněné tričko s motivem Velorex - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Trika mají krátký rukáv, kulatý výstřih a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka je ze 100% bavlny a díky vyšší gramáži je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Tričko Velorex',
                'post_seo_description' => 'Černé tričko s krátkým rukávem a s motivem Velorex ze 100% bavlny.',
                'post_seo_keywords' => 'jawa, jawa tričko, jawa dárek, velorex, tričko velorex',
                'term' => 1,
            ],10 => [
                'title' => 'Mikina Jawa 50/23 Mustang',
                'teaser' => 'Černá mikina s kapucí a s motivem Jawa Mustang. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černá mikina s kapucí a s motivem Jawa 50/23 Mustang - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Mikiny mají kapuci a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka má vyšší gramáž a je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Mikina Jawa 50/23 Mustang',
                'post_seo_description' => 'Kvalitní černá mikina s kapucí a s motivem Jawa Mustang.',
                'post_seo_keywords' => 'jawa, jawa mikina, jawa dárek, jawa mustang, jawa 23, jawa 50, jawa 50/23',
                'term' => 2,
            ],11 => [
                'title' => 'Mikina Jawa 50/20 Pionýr',
                'teaser' => 'Černá mikina s kapucí a s motivem Jawa Pionýr. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černá mikina s kapucí a s motivem Jawa 50/20 Pionýr - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Mikiny mají kapuci a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka má vyšší gramáž a je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Mikina Jawa 50/20 Pionýr',
                'post_seo_description' => 'Kvalitní černá mikina s kapucí a s motivem Jawa Pionýr.',
                'post_seo_keywords' => 'jawa, jawa mikina, jawa dárek, jawa pionýr, jawa 20, jawa 50, jawa 50/20',
                'term' => 2,
            ],13 => [
                'title' => 'Mikina Jawa 50/21 Pionýr',
                'teaser' => 'Černá mikina s kapucí a s motivem Jawa Pionýr. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černá mikina s kapucí a s motivem Jawa 50/21 Pionýr - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Mikiny mají kapuci a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka má vyšší gramáž a je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Mikina Jawa 50/21 Pionýr',
                'post_seo_description' => 'Kvalitní černá mikina s kapucí a s motivem Jawa Pionýr.',
                'post_seo_keywords' => 'jawa, jawa mikina, jawa dárek, jawa pionýr, jawa 21, jawa 50, jawa 50/21',
                'term' => 2,
            ],15 => [
                'title' => 'Mikina Jawa 50/555 Pařez',
                'teaser' => 'Černá mikina s kapucí a s motivem Jawa Pařez. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černá mikina s kapucí a s motivem Jawa 50/555 Pařez - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Mikiny mají kapuci a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka má vyšší gramáž a je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Mikina Jawa 50/555 Pařez',
                'post_seo_description' => 'Kvalitní černá mikina s kapucí a s motivem Jawa Pařez.',
                'post_seo_keywords' => 'jawa, jawa mikina, jawa dárek, jawa pionyr, jawa pařez, jawa 555, jawa 50, jawa 50/555',
                'term' => 2,
            ],16 => [
                'title' => 'Mikina Stadion S11',
                'teaser' => 'Černá mikina s kapucí a s motivem Stadion S11. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černá mikina s kapucí a s motivem Stadion S11 - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Mikiny mají kapuci a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka má vyšší gramáž a je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Mikina Stadion S11',
                'post_seo_description' => 'Kvalitní černá mikina s kapucí a s motivem Stadion S11.',
                'post_seo_keywords' => 'jawa, jawa mikina, jawa dárek, stadion, stadion s11',
                'term' => 2,
            ],17 => [
                'title' => 'Mikina Stadion S22',
                'teaser' => 'Černá mikina s kapucí a s motivem Stadion S22. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černá mikina s kapucí a s motivem Stadion S22 - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Mikiny mají kapuci a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka má vyšší gramáž a je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Mikina Stadion S22',
                'post_seo_description' => 'Kvalitní černá mikina s kapucí a s motivem Stadion S22.',
                'post_seo_keywords' => 'jawa, jawa mikina, jawa dárek, stadion, stadion s22',
                'term' => 2,
            ],18 => [
                'title' => 'Mikina Babetta 207',
                'teaser' => 'Černá mikina s kapucí a s motivem Babetta 207. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černá mikina s kapucí a s motivem Babetta 207 - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Mikiny mají kapuci a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka má vyšší gramáž a je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Mikina Babetta 207',
                'post_seo_description' => 'Kvalitní černá mikina s kapucí a s motivem Babetta 207.',
                'post_seo_keywords' => 'jawa, jawa mikina, jawa dárek, babetta, babetta 207',
                'term' => 2,
            ],19 => [
                'title' => 'Mikina Babetta 210',
                'teaser' => 'Černá mikina s kapucí a s motivem Babetta 210. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černá mikina s kapucí a s motivem Babetta 210 - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Mikiny mají kapuci a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka má vyšší gramáž a je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Mikina Babetta 210',
                'post_seo_description' => 'Kvalitní černá mikina s kapucí a s motivem Babetta 210.',
                'post_seo_keywords' => 'jawa, jawa mikina, jawa dárek, babetta, babetta 210',
                'term' => 2,
            ],110 => [
                'title' => 'Mikina Jawa Kývačka',
                'teaser' => 'Černá mikina s kapucí a s motivem Jawa Kývačka. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černá mikina s kapucí a s motivem Jawa Kývačka - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Mikiny mají kapuci a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka má vyšší gramáž a je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Mikina Jawa Kývačka',
                'post_seo_description' => 'Kvalitní černá mikina s kapucí a s motivem Jawa Kývačka.',
                'post_seo_keywords' => 'jawa, jawa mikina, jawa dárek, kývačka, jawa kývačka',
                'term' => 2,
            ],111 => [
                'title' => 'Mikina Jawa Panelka',
                'teaser' => 'Černá mikina s kapucí a s motivem Jawa Panelka. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černá mikina s kapucí a s motivem Jawa Panelka - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Mikiny mají kapuci a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka má vyšší gramáž a je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Mikina Jawa Panelka',
                'post_seo_description' => 'Kvalitní černá mikina s kapucí a s motivem Jawa Panelka.',
                'post_seo_keywords' => 'jawa, jawa mikina, jawa dárek, panelka, jawa panelka, jawa 250',
                'term' => 2,
            ],112 => [
                'title' => 'Mikina Jawa Pérák',
                'teaser' => 'Černá mikina s kapucí a s motivem Jawa Pérák. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černá mikina s kapucí a s motivem Jawa Pérák - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Mikiny mají kapuci a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka má vyšší gramáž a je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Mikina Jawa Pérák',
                'post_seo_description' => 'Kvalitní černá mikina s kapucí a s motivem Jawa Pérák.',
                'post_seo_keywords' => 'jawa, jawa mikina, jawa dárek, pérák, jawa pérák, jawa 250',
                'term' => 2,
            ],113 => [
                'title' => 'Mikina Jawa 350/634 Konopnice',
                'teaser' => 'Černá mikina s kapucí a s motivem Jawa 350/634 Konopnice. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černá mikina s kapucí a s motivem Jawa 350/634 Konopnice - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Mikiny mají kapuci a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka má vyšší gramáž a je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Mikina Jawa 350/634 Konopnice',
                'post_seo_description' => 'Kvalitní černá mikina s kapucí a s motivem Jawa 350/634 Konopnice.',
                'post_seo_keywords' => 'jawa, jawa mikina, jawa dárek, konopnice, jawa konopnice, jawa 350, jawa 350/634, 350/634',
                'term' => 2,
            ],114 => [
                'title' => 'Mikina Jawa 350/638',
                'teaser' => 'Černá mikina s kapucí a s motivem Jawa 350/638. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černá mikina s kapucí a s motivem Jawa 350/638 - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Mikiny mají kapuci a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka má vyšší gramáž a je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Mikina Jawa 350/638',
                'post_seo_description' => 'Kvalitní černá mikina s kapucí a s motivem Jawa 350/638.',
                'post_seo_keywords' => 'jawa, jawa mikina, jawa dárek, jawa 350, jawa 350/638, 350/638',
                'term' => 2,
            ],116 => [
                'title' => 'Mikina Jawa 500 OHC',
                'teaser' => 'Černá mikina s kapucí a s motivem Jawa 500 OHC. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černá mikina s kapucí a s motivem Jawa 500 OHC - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Mikiny mají kapuci a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka má vyšší gramáž a je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Mikina Jawa 500 OHC',
                'post_seo_description' => 'Kvalitní černá mikina s kapucí a s motivem Jawa 500 OHC.',
                'post_seo_keywords' => 'jawa, jawa mikina, jawa dárek, jawa 500, jawa 500 ohc, 500 ohc',
                'term' => 2,
            ],117 => [
                'title' => 'Mikina ČZ 175/501 Prase',
                'teaser' => 'Černá mikina s kapucí a s motivem ČZ 175/501 Prase. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černá mikina s kapucí a s motivem ČZ 175/501 (502, 505) Prase - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Mikiny mají kapuci a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka má vyšší gramáž a je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Mikina ČZ 175/501 Prase',
                'post_seo_description' => 'Kvalitní černá mikina s kapucí a s motivem ČZ 175/501 Prase.',
                'post_seo_keywords' => 'jawa, jawa mikina, jawa dárek, čz, čezeta, čz 175, čz 501, čz 502, čz 505, čz 175/501, 175/501, mikina čezeta, mikina čz',
                'term' => 2,
            ],118 => [
                'title' => 'Mikina ČZ 125/476, 175/477',
                'teaser' => 'Černá mikina s kapucí a s motivem ČZ 125/476, 175/477. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černá mikina s kapucí a s motivem ČZ 125/476, 175/477 - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Mikiny mají kapuci a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka má vyšší gramáž a je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Mikina ČZ 125/476, 175/477',
                'post_seo_description' => 'Kvalitní černá mikina s kapucí a s motivem ČZ 125/476, 175/477.',
                'post_seo_keywords' => 'jawa, jawa mikina, jawa dárek, čz, čezeta, čz 175, čz 125, čz 476, čz 477, 125/476, 175/477, mikina čezeta, mikina čz',
                'term' => 2,
            ],119 => [
                'title' => 'Mikina ČZ 125/487, 175/488',
                'teaser' => 'Černá mikina s kapucí a s motivem ČZ 125/487, 175/488. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černá mikina s kapucí a s motivem ČZ 125/487, 175/488 - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Mikiny mají kapuci a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka má vyšší gramáž a je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Mikina ČZ 125/487, 175/488',
                'post_seo_description' => 'Kvalitní černá mikina s kapucí a s motivem ČZ 125/487, 175/488.',
                'post_seo_keywords' => 'jawa, jawa mikina, jawa dárek, čz, čezeta, čz 175, čz 125, čz 487, čz 488, 125/487, 175/488, mikina čezeta, mikina čz',
                'term' => 2,
            ],120 => [
                'title' => 'Mikina Simson S51',
                'teaser' => 'Černá mikina s kapucí a s motivem Simson S51. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černá mikina s kapucí a s motivem Simson S51 - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Mikiny mají kapuci a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka má vyšší gramáž a je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Mikina Simson S51',
                'post_seo_description' => 'Kvalitní černá mikina s kapucí a s motivem Simson S51.',
                'post_seo_keywords' => 'jawa, jawa mikina, jawa dárek, simson, simson s51, s51, mikina simson s51',
                'term' => 2,
            ],121 => [
                'title' => 'Mikina MZ 150',
                'teaser' => 'Černá mikina s kapucí a s motivem MZ 150. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černá mikina s kapucí a s motivem MZ 150 - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Mikiny mají kapuci a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka má vyšší gramáž a je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Mikina MZ 150',
                'post_seo_description' => 'Kvalitní černá mikina s kapucí a s motivem MZ 150.',
                'post_seo_keywords' => 'jawa, jawa mikina, jawa dárek, mz 150, mikina mz 150',
                'term' => 2,
            ],122 => [
                'title' => 'Mikina Velorex',
                'teaser' => 'Černá mikina s kapucí a s motivem Velorex. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černá mikina s kapucí a s motivem Velorex - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Mikiny mají kapuci a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka má vyšší gramáž a je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Mikina Velorex',
                'post_seo_description' => 'Kvalitní černá mikina s kapucí a s motivem Velorex.',
                'post_seo_keywords' => 'jawa, jawa mikina, jawa dárek, velorex, mikina velorex',
                'term' => 2,
            ],221 => [
                'title' => 'Tričko Jawa 50 Pionýr',
                'teaser' => 'Černé tričko s krátkým rukávem a s motivem Jawa 50 Pionýr ze 100% bavlny. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černé bavlněné tričko s motivem Jawa 50 Pionýr - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Trika mají krátký rukáv, kulatý výstřih a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka je ze 100% bavlny a díky vyšší gramáži je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Tričko Jawa 50 Pionýr',
                'post_seo_description' => 'Černé tričko s krátkým rukávem a s motivem Jawa 50 Pionýr ze 100% bavlny.',
                'post_seo_keywords' => 'jawa, jawa tričko, jawa dárek, jawa 50, jawa 50 pionýr, jawa 50/21',
                'term' => 3,
            ],222 => [
                'title' => 'Tričko Jawa 250',
                'teaser' => 'Černé tričko s krátkým rukávem a s motivem Jawa 250 ze 100% bavlny. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černé bavlněné tričko s motivem Jawa 250 - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Trika mají krátký rukáv, kulatý výstřih a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka je ze 100% bavlny a díky vyšší gramáži je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Tričko Jawa 250',
                'post_seo_description' => 'Černé tričko s krátkým rukávem a s motivem Jawa 250 ze 100% bavlny.',
                'post_seo_keywords' => 'jawa, jawa tričko, jawa dárek, jawa 250',
                'term' => 3,
            ],223 => [
                'title' => 'Tričko Jawa 350/634',
                'teaser' => 'Černé tričko s krátkým rukávem a s motivem Jawa 350/634 ze 100% bavlny. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černé bavlněné tričko s motivem Jawa 350/634 - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Trika mají krátký rukáv, kulatý výstřih a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka je ze 100% bavlny a díky vyšší gramáži je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Tričko Jawa 350/634',
                'post_seo_description' => 'Černé tričko s krátkým rukávem a s motivem Jawa 350/634 ze 100% bavlny.',
                'post_seo_keywords' => 'jawa, jawa tričko, jawa dárek, jawa 350/634',
                'term' => 3,
            ],224 => [
                'title' => 'Tričko Babetta 210',
                'teaser' => 'Černé tričko s krátkým rukávem a s motivem Babetta 210 ze 100% bavlny. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černé bavlněné tričko s motivem Babetta 210 - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Trika mají krátký rukáv, kulatý výstřih a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka je ze 100% bavlny a díky vyšší gramáži je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Tričko Babetta 210',
                'post_seo_description' => 'Černé tričko s krátkým rukávem a s motivem Babetta 210 ze 100% bavlny.',
                'post_seo_keywords' => 'jawa, jawa tričko, jawa dárek, babetta 210, babetta',
                'term' => 3,
            ],225 => [
                'title' => 'Tričko Stadion S11',
                'teaser' => 'Černé tričko s krátkým rukávem a s motivem Stadion S11 ze 100% bavlny. Tisknuto kvalitním sítotiskem. Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.',
                'value' => '<p>Černé bavlněné tričko s motivem Stadion S11 - legendární motorkou z 20. století, která si získala nadšence napříč všemi generacemi. Motiv je tištěn pomocí technologie sítotisku, díky čemuž je potisk kvalitnější. Motivy jsou detailnější a taky v lepším rozlišení. </p><br><p>Trika mají krátký rukáv, kulatý výstřih a jsou unisex – vhodná jak pro muže, tak i pro ženy. Látka je ze 100% bavlny a díky vyšší gramáži je pevnější a odolnější.</p><br><p>Vhodné jako dárek pro vás či Vaše blízké. Zkrátka pro všechny, kteří ocení kvalitu a originalitu.</p>',
                'post_seo_title' => 'Tričko Stadion S11',
                'post_seo_description' => 'Černé tričko s krátkým rukávem a s motivem Stadion S11 ze 100% bavlny.',
                'post_seo_keywords' => 'jawa, jawa tričko, jawa dárek, stadion s11, tričko stadion, s11',
                'term' => 3,
            ]
        ];

        foreach($data as $item) {
            $post = Post::create([
                'collection_name' => 'product',
                'status' => 'published',
                'tmp' => 0
            ]);
            $post->versions()->create([
                'name' => 'main',
                'label' => 'Hlavní verze',
            ]);
            $post->locales()->create([
                'locale_name' => 'cs',
                'post_title' => $item['title'],
                'post_slug' => Str::slug($item['title'], '-'),
                'post_teaser' => $item['teaser'],
                'post_custom_teaser' => 1,
                'post_value' => $item['value'],
                'post_seo_title' => $item['post_seo_title'],
                'post_seo_description' => $item['post_seo_description'],
                'post_seo_keywords' => $item['post_seo_keywords'],
                'version_name' => 'main',
            ]);
            $post->terms()->sync([$item['term']]);

            if($item['term'] == 1) {
                $buy_price = 105;
                $price = 329.00;
                $priceEur = 12.99;
            }elseif($item['term'] == 2) {
                $buy_price = 350;
                $price = 699.00;
                $priceEur = 27.49;
            }else {
                $buy_price = 100;
                $price = 199.00;
                $priceEur = 7.99;
            }

            $sizes = ['S','M','L','XL','2XL','3XL'];

            foreach($sizes as $size) {
                $item = Item::create([
                    'post_id' => $post->id,
                    'sub_name' => $size,
                    'weight' => '0.124',
                    'weight_unit' => 'kg',
                    'width' => 0,
                    'width_unit' => 'cm',
                    'height' => 0,
                    'height_unit' => 'cm',
                    'depth' => 0,
                    'depth_unit' => 'cm',
                    'buy_price' => $buy_price,
                    'buy_price_unit' => 'Kč',
                    'quantity' => 10,
                    'active' => 1
                ]);
                $item->currencies()->create([
                    'locale_name' => 'cs',
                    'price' => $price,
                    'price_VAT' => $price,
                    'VAT' => 0,
                    'active' => 1
                ]);
                $item->currencies()->create([
                    'locale_name' => 'sk',
                    'price' => $priceEur,
                    'price_VAT' => $priceEur,
                    'VAT' => 0,
                    'active' => 1
                ]);
            }
        }
    }
}